name: Create Release from package.json

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  create_release:
    runs-on: windows-latest  # Use Windows environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Read version from package.json using Node.js
      - name: Get version from package.json
        id: version
        run: |
          node -p "require('./package.json').version" > version.txt
          echo "VERSION=$(type version.txt)" >> $env:GITHUB_ENV
        shell: powershell

      # Step 3: Create draft GitHub release using version from package.json
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub token for authentication
        with:
          tag_name: "v${{ env.VERSION }}"  # Version from package.json
          release_name: "v${{ env.VERSION }}"  # Use the same version for the release name
          draft: true  # This ensures the release is created as a draft
          prerelease: false  # Set to true if it's a pre-release
